import pygame
smallfont = pygame.font.SysFont('Corbel', 35)
class ColorsAndText:
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLUE = (0, 0, 255)
    GREY = (192,192,192)
    PINK = (255,182,193)
    CYAN = (0,255,255)
    ORANGE = (255,165,0)
    PURPLE = (186,85,211)
    
    def __init__(self):
        texts = []
        header1 = smallfont.render('Background Color', True, buttonText)
        texts.append(header1)
        color1 = smallfont.render('Black', True, buttonText)
        texts.append(color1)
        color2 = smallfont.render('White', True, buttonText)
        texts.append(color2)
        color3 = smallfont.render('Blue', True, buttonText)
        texts.append(color3)
        color4 = smallfont.render('Red', True, buttonText)
        texts.append(color4)
        color5 = smallfont.render('Green', True, buttonText)
        texts.append(color5)
        color6 = smallfont.render('Grey', True, buttonText)
        texts.append(color6)
        color7 = smallfont.render('Pink', True, buttonText)
        texts.append(color7)
        color8 = smallfont.render('Cyan', True, buttonText)
        texts.append(color8)
        color9 = smallfont.render('Orange', True, buttonText)
        texts.append(color9)
        color10 = smallfont.render('Purple', True, buttonText)
        texts.append(color10)